import { normalizeLocale } from './core.js';

const copy = {
  en: {
    subtitle: 'Open-source BYOK · basic reverse only', settings: 'Settings', upload: 'Choose an image', drop: 'Drop or paste an image here', analyze: 'Reverse prompt', working: 'Analyzing…', palette: 'Local palette', result: 'Basic result', summary: 'Summary', prompt: 'Original prompt', ratio: 'Suggested ratio', translate: 'Translate for reading', translated: 'Translation preview', sameLanguage: 'The prompt already matches the interface language.', translationNote: 'Reading aid only. The original prompt is never replaced.', history: 'Local history', empty: 'No local history yet.', configure: 'Configure an endpoint, model and API key first.', failed: 'Analysis failed.', remotePalette: 'Upload the image to calculate a local palette.', copied: 'Copied', copy: 'Copy', noGeneration: 'Lite does not generate images. EYROVE Prompt Pro adds private advanced analysis and generation.'
  },
  'zh-CN': {
    subtitle: '开源 BYOK · 仅基础反推', settings: '设置', upload: '选择图片', drop: '拖入或粘贴图片', analyze: '基础反推', working: '分析中…', palette: '本地色卡', result: '基础结果', summary: '摘要', prompt: '原始提示词', ratio: '建议画幅', translate: '翻译便于阅读', translated: '翻译预览', sameLanguage: '提示词与当前界面语言一致，无需翻译。', translationNote: '仅用于阅读理解，永远不会替换原提示词。', history: '本地历史', empty: '暂无本地历史。', configure: '请先配置接口、模型和 API Key。', failed: '分析失败。', remotePalette: '请上传图片以计算本地色卡。', copied: '已复制', copy: '复制', noGeneration: 'Lite 不提供生图；EYROVE Prompt Pro 提供私有高级反推与生图。'
  },
  ja: { subtitle:'オープンソース BYOK・基本解析のみ',settings:'設定',upload:'画像を選択',drop:'画像をドロップまたは貼り付け',analyze:'基本プロンプト解析',working:'分析中…',palette:'ローカルパレット',result:'基本結果',summary:'概要',prompt:'元のプロンプト',ratio:'推奨比率',translate:'閲覧用に翻訳',translated:'翻訳プレビュー',sameLanguage:'プロンプトは現在の表示言語と同じです。',translationNote:'閲覧用のみ。元のプロンプトは置き換えません。',history:'ローカル履歴',empty:'履歴はまだありません。',configure:'先にエンドポイント、モデル、API Key を設定してください。',failed:'分析に失敗しました。',remotePalette:'ローカルパレットを計算するには画像をアップロードしてください。',copied:'コピー済み',copy:'コピー',noGeneration:'Lite は画像を生成しません。Pro は非公開の高度解析と生成を提供します。' },
  ko: { subtitle:'오픈소스 BYOK · 기본 역분석만',settings:'설정',upload:'이미지 선택',drop:'이미지를 놓거나 붙여넣기',analyze:'기본 프롬프트 역분석',working:'분석 중…',palette:'로컬 색상표',result:'기본 결과',summary:'요약',prompt:'원본 프롬프트',ratio:'권장 비율',translate:'읽기용 번역',translated:'번역 미리보기',sameLanguage:'프롬프트가 현재 인터페이스 언어와 같습니다.',translationNote:'읽기용이며 원본 프롬프트를 대체하지 않습니다.',history:'로컬 기록',empty:'로컬 기록이 없습니다.',configure:'먼저 엔드포인트, 모델, API Key를 설정하세요.',failed:'분석에 실패했습니다.',remotePalette:'로컬 색상표를 계산하려면 이미지를 업로드하세요.',copied:'복사됨',copy:'복사',noGeneration:'Lite는 이미지를 생성하지 않습니다. Pro는 비공개 고급 분석과 생성을 제공합니다.' },
  de: { subtitle:'Open Source BYOK · nur Basisanalyse',settings:'Einstellungen',upload:'Bild wählen',drop:'Bild ablegen oder einfügen',analyze:'Prompt rekonstruieren',working:'Analyse läuft…',palette:'Lokale Palette',result:'Basisergebnis',summary:'Zusammenfassung',prompt:'Original-Prompt',ratio:'Empfohlenes Format',translate:'Zum Lesen übersetzen',translated:'Übersetzungsvorschau',sameLanguage:'Der Prompt entspricht bereits der Oberflächensprache.',translationNote:'Nur als Lesehilfe; der Original-Prompt bleibt erhalten.',history:'Lokaler Verlauf',empty:'Noch kein lokaler Verlauf.',configure:'Zuerst Endpunkt, Modell und API Key konfigurieren.',failed:'Analyse fehlgeschlagen.',remotePalette:'Bild hochladen, um eine lokale Palette zu berechnen.',copied:'Kopiert',copy:'Kopieren',noGeneration:'Lite generiert keine Bilder. Pro bietet private erweiterte Analyse und Generierung.' },
  fr: { subtitle:'BYOK open source · analyse simple',settings:'Réglages',upload:'Choisir une image',drop:'Déposez ou collez une image',analyze:'Reconstruire le prompt',working:'Analyse…',palette:'Palette locale',result:'Résultat simple',summary:'Résumé',prompt:'Prompt original',ratio:'Ratio conseillé',translate:'Traduire pour lire',translated:'Aperçu traduit',sameLanguage:'Le prompt correspond déjà à la langue de l’interface.',translationNote:'Aide à la lecture uniquement; le prompt original reste intact.',history:'Historique local',empty:'Aucun historique local.',configure:'Configurez d’abord le point d’accès, le modèle et la clé API.',failed:'Échec de l’analyse.',remotePalette:'Importez l’image pour calculer une palette locale.',copied:'Copié',copy:'Copier',noGeneration:'Lite ne génère pas d’images. Pro ajoute une analyse avancée privée et la génération.' },
  es: { subtitle:'BYOK de código abierto · análisis básico',settings:'Ajustes',upload:'Elegir imagen',drop:'Arrastra o pega una imagen',analyze:'Reconstruir prompt',working:'Analizando…',palette:'Paleta local',result:'Resultado básico',summary:'Resumen',prompt:'Prompt original',ratio:'Proporción sugerida',translate:'Traducir para leer',translated:'Vista previa traducida',sameLanguage:'El prompt ya coincide con el idioma de la interfaz.',translationNote:'Solo ayuda de lectura; el prompt original no se sustituye.',history:'Historial local',empty:'Aún no hay historial local.',configure:'Configura primero endpoint, modelo y API Key.',failed:'Falló el análisis.',remotePalette:'Sube la imagen para calcular una paleta local.',copied:'Copiado',copy:'Copiar',noGeneration:'Lite no genera imágenes. Pro añade análisis avanzado privado y generación.' }
};

export function translator(locale) {
  const dictionary = copy[normalizeLocale(locale)] || copy.en;
  return (key) => dictionary[key] || copy.en[key] || key;
}
